# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2iQdaWoUWrheW0F5ODh8M1lIuqDJbb8
"""

import pandas as pd
import numpy as np
import io
import pandas_profiling

retail_raw = pd.read_csv('file_name.csv')

retail_raw

retail_raw.to_csv('file_name.csv', encoding='utf-8')

# Kolom city
length_city = len(retail_raw['city'])
count_city = retail_raw['city'].count()
# Kolom product id
length_product_id = len(retail_raw['product_id'])
count_product_id = retail_raw['product_id'].count()

length_city

count_city

length_product_id

count_product_id

# Missing value pada kolom city
number_of_missing_values_city = length_city - count_city
ratio_of_missing_values_city = number_of_missing_values_city/length_city

# Tugas praktek: Missing value pada kolom product_id
number_of_missing_values_product_id = length_product_id - count_product_id
ratio_of_missing_values_product_id = number_of_missing_values_product_id / length_product_id

number_of_missing_values_city

number_of_missing_values_product_id

ratio_of_missing_values_city

ratio_of_missing_values_product_id

pct_of_missing_values_city = '{0:.1f}%'.format(ratio_of_missing_values_city * 100)
print('Persentase missing value kolom city:', pct_of_missing_values_city)

pct_of_missing_values_product_id = '{0:.1f}%'.format(ratio_of_missing_values_product_id * 100)
print('Persentase missing value kolom product_id:', pct_of_missing_values_product_id)